version: '3'

services:
   eureka-server:
     image: discoveryservice:latest
     restart: always
     ports:
       - "8761:8761"

   movie-catalog-service:
     depends_on:
       - eureka-server
     image: movie-catalog-service:latest
     ports:
       - "8081:8081"
     restart: always
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

       
   movie-info-service:
     depends_on:
       - eureka-server
     image: movie-info-service:latest
     ports:
       - "8082:8082"
     restart: always
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

       
   ratings-data-service:
     depends_on:
       - eureka-server
     image: ratings-data-service:latest
     ports:
       - "8083:8083"
     restart: always
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka



    